language: c
sudo: required
dist: trusty
services:
  - docker
install:
  - mkdir .opam
  - docker-compose run ocaml bash -e .travis/install
script:
  - docker-compose run ocaml bash -e .travis/test
matrix:
  fast_finish: true
notifications:
  email: false
