#!/usr/bin/env bash

eval $(opam config env)

opam install -y oasis ssl lwt_ssl ocamlfind atdgen cmdliner process oUnit cohttp lwt

make distclean
make configure CONFIGUREFLAGS=--enable-tests
make test
